### ISSUE TITLE
The version for browser has a bug in Firefox

### ISSUE THREAD

**Issue by cypher-m** [MitocGroup/deep-framework#108]
In Chrome it works without errors
deep-framework@1.1.3

![selection_001](https://cloud.githubusercontent.com/assets/7883636/11272837/7919cf2c-8ed8-11e5-9a82-8982303c8b41.png)

**Comment by AlexanderC** [comment]
This issue would be fixed in the next patch version of deep-framework. The issue root cause is that Firefox adds to `application/json` content type header an `; charset=UTF-8` suffix resulting to a `application/json; charset=UTF-8` header that breakes the aws4 signature check on ApiGateway side.
