### ISSUE TITLE
Benchmark Lambdas performance 

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/deep-framework#139]
Manual benchmarking (10 runs each step, min/avg/max):
- Run with/out babel-polyfill
- Run different lambda sizes (with some unused garbages) [x5 sizes]
- Run different lambda sizes (use the included code) [x5 sizes]
- Run Dynamo+S3 write with/out deep-framework

**Comment by mgoria** [comment]
Related task -> https://github.com/MitocGroup/deep-framework/issues/140

**Comment by mgoria** [comment]
This functionality was moved into separate repo https://github.com/MitocGroup/deep-microservices-benchmarking, all further issues will be reported there.
