### ISSUE TITLE
Investigate the cost of transpiling es2015 code into es5

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/deep-framework#225]
Take a look at https://github.com/paulirish/The-cost-of-transpiling-es2015-in-2016 and find out if it make sense to use another transpilers.

**Comment by CCristi** [comment]
Task [progress](https://gist.github.com/CCristi/4ddf07fd69480092f4bc).
Researching the other sollutions for frontend (closure, webpack).

**Comment by eistrati** [comment]
Not relevant anymore
