### ISSUE TITLE
DEEP is not opening on new Chrome version with 'Converting circular structure to JSON' error

### ISSUE THREAD

**Issue by dsasov** [MitocGroup/deep-framework#261]
Bug reproduces only on the newest Chrome version(Version 49.0.2623.75) on Linux.
See attached: 'Converting circular structure to JSON' error is in console and Sentry sends a message: https://app.getsentry.com/hearstcorp/digital-platform-prod/issues/114875839/

![screenshot from 2016-03-03 12 00 44](https://cloud.githubusercontent.com/assets/10956412/13491344/9a06dafe-e13a-11e5-9c51-df3be50171a6.png)

**Comment by mgoria** [comment]
This issue is fixed in `deep-framework@1.8.4` version.
