### ISSUE TITLE
npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\user\AppData\Roaming\npm\node_modules\deepify\bin\commands' on Windows

### ISSUE THREAD

**Issue by eistrati** [MitocGroup/deep-framework#273]
C:\Users\user>npm install deepify -g
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\
node_modules\\npm\\bin\\npm-cli.js" "install" "deepify" "-g"
npm ERR! node v4.3.1
npm ERR! npm  v2.14.12
npm ERR! path C:\Users\user\AppData\Roaming\npm\node_modules\deepify\bin\com
mands
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rmdir

npm ERR! EBUSY: resource busy or locked, rmdir 'C:\Users\user\AppData\Roamin
g\npm\node_modules\deepify\bin\commands'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>
npm ERR! error rolling back Error: EBUSY: resource busy or locked, rmdir 'C:\Use
rs\user\AppData\Roaming\npm\node_modules\deepify\bin\commands'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  { [Error: EBUSY: resource busy or locked, rmdir 'C:
\Users\user\AppData\Roaming\npm\node_modules\deepify\bin\commands']
npm ERR! error rolling back   errno: -4082,
npm ERR! error rolling back   code: 'EBUSY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: 'C:\\Users\\user\\AppData\\Roaming\\npm\
\node_modules\\deepify\\bin\\commands' }

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\npm-debug.log

**Comment by eistrati** [comment]
We were able to reproduce this issue again and working now to add more check points in place. Regarding the earlier issue with `code EBUSY errno -4082`, it looks like this is a known issue and we'll keep monitoring it as well: https://github.com/npm/npm/issues/7370 (somebody suggests reboot or kill all npm processes)

**Comment by dbaldon** [comment]
I'm getting a similar error but the action appears to be "rename" rather than "rmdir". If I'm reading this correctly the directory that is to be renamed is the directory I've CD'd to (in the command window). I'm in that directory so that npm can find package.json. Otherwise I get different errors.
```
C:\Users\user\AppData\Roaming\npm\node_modules\npm-windows-upgrade>npm install -g -ember-cli@1.13.13
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "-ember-cli@1.13.13"
npm ERR! node v4.4.7
npm ERR! npm  v3.3.12
npm ERR! path C:\Users\user\AppData\Roaming\npm\node_modules\npm-windows-upgrade
npm ERR! code EBUSY
npm ERR! errno -4082
npm ERR! syscall rename

npm ERR! EBUSY: resource busy or locked, rename 'C:\Users\user\AppData\Roaming\npm\node_modules\npm-windows-upgrade' -> 'C:\Users\user\AppData\Roaming\npm\node_modules\.npm-w
indows-upgrade.DELETE'
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\user\AppData\Roaming\npm\node_modules\npm-windows-upgrade\npm-debug.log
```

**Comment by eistrati** [comment]
@dbaldon I have checked https://github.com/npm/npm/issues/7370 and it doesn't look like npm folks were able to solve this issue. Can you please try to use node v6+ on Windows and see if this problem persists?

**Comment by dbaldon** [comment]
I deleted my comment because I figured out that I had entered the command
incorrectly. I had inadvertently put a dash (-) in front of
ember-cli@1.13.13 which caused the argument to be ignored and npm thought
it was being told to install (upgrade?) itself.

**Comment by eistrati** [comment]
@dbaldon Thanks for getting to the bottom of the problem and sharing your findings. We'll try to learn from your experience and add some extra validations to avoid similar issues in future.

**Comment by adirzoari** [comment]
@eistrati i have the same problem, have your resolved it?

> C:\Users\Adir\MyApps\tasklist>ionic serve
shell.js: internal error
Error: EBUSY: resource busy or locked, open 'C:\Users\Adir\AppData\Local\Temp\shelljs_93017b21a57964622e1d'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.fs.writeFileSync (fs.js:1333:33)
    at execSync (C:\Users\Adir\AppData\Roaming\npm\node_modules\ionic\node_modules\shelljs\src\exec.js:67:57)
    at Object._exec (C:\Users\Adir\AppData\Roaming\npm\node_modules\ionic\node_modules\shelljs\src\exec.js:179:12)
    at Object.exec (C:\Users\Adir\AppData\Roaming\npm\node_modules\ionic\node_modules\shelljs\src\common.js:168:23)
    at Object.gatherGulpInfo (C:\Users\Adir\AppData\Roaming\npm\node_modules\ionic\node_modules\ionic-app-lib\lib\info.js:201:24)
    at Object.t (C:\Users\Adir\AppData\Roaming\npm\node_modules\ionic\lib\utils\stats.js:148:15)
    at Object.run (C:\Users\Adir\AppData\Roaming\npm\node_modules\ionic\lib\cli.js:135:16)
    at Object.<anonymous> (C:\Users\Adir\AppData\Roaming\npm\node_modules\ionic\bin\ionic:13:10)

**Comment by eistrati** [comment]
@adirzoari It looks like an issue with npm on windows. Check out below link and see if it solves your problem: https://github.com/npm/npm/issues/7370

**Comment by haroldjcastillo** [comment]
I resolved with `npm cache clean` or with meteor 'meteor npm cache clean'

**Comment by HectorRPL** [comment]
@haroldjcastillo haroldjcastillo thanks! works for me

**Comment by Ahtesham519** [comment]
"npm cache clean"  works for me 👍  
i also re-installed the meteor .

**Comment by abhishek11210646** [comment]
worked for me by uninstalling antivirus (bytefence antivirus).

**Comment by danielpk74** [comment]
It works for me with "npm rebuild", "npm cache clear --for", "npm install"

**Comment by alloygodwin1** [comment]
In Windows 10 64-bit OS, I have resolved this issue by uninstalling Anti-Malware software.

**Comment by karthick-srinivasan** [comment]
In my case, i just restarted my machine and now its working.

**Comment by dgpro** [comment]
Nothing worked for me until I removed all the packages from `package.json` and installed them manually `npm install -D package1 package2 packageN` (`-D` for `devDependencies` only). Apparently some of them were outdated and required old dependencies which were breaking things.

**Comment by neudesicchetan** [comment]
CLose CMD prompts/ Powershell or folder explore on that path . Try again . Will work .

**Comment by antonpegov** [comment]
> CLose CMD prompts/ Powershell or folder explore on that path . Try again . Will work .

Definately not
