### ISSUE TITLE
deepify helloworld

### ISSUE THREAD

**Issue by PaulStAmand** [MitocGroup/deep-framework#274]
Windows 7
git-bash 2.7.2
node v4.4.0
npm 2.14.20
deepify v1.7.9

user@user-3 MINGW64 ~
$ deepify server deep-hello-world
23:19:58 GMT-0500 (Eastern Standard Time)  No init hook found for microservice hello.world.example
23:19:58 GMT-0500 (Eastern Standard Time)  Running init hook for microservice deep.ng.root
Installing latest deep-framework from GitHub
######################################################################## 100.0%
23:20:12 GMT-0500 (Eastern Standard Time)  Running "npm install" on 1 Lambdas
npm WARN package.json say-hello-world@0.0.1 No README data

> say-hello-world@0.0.1 postinstall C:\Users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello
> npm run compile

> say-hello-world@0.0.1 compile C:\Users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello
> deepify compile-es6 `pwd`

23:21:50 GMT-0500 (Eastern Standard Time)  Start linking aws-sdk
C:\Users\user\deep-hello-world\deep-microservices-helloworld\Backend\src\SayHello\node_modules\aws-sdk -> C:\Users\user\AppData\Roaming\npm\node_modules\aws-sdk
23:22:47 GMT-0500 (Eastern Standard Time)  No "server before init hook" found in hello.world.example
23:22:47 GMT-0500 (Eastern Standard Time)  No "server before init hook" found in deep.ng.root
23:22:47 GMT-0500 (Eastern Standard Time)  Booting local FS
23:22:47 GMT-0500 (Eastern Standard Time)  Linking custom validation schemas
23:22:49 GMT-0500 (Eastern Standard Time)  Creating server on port 8000
23:22:49 GMT-0500 (Eastern Standard Time)  HTTP Server is up and running!
23:22:49 GMT-0500 (Eastern Standard Time)  Creating local DynamoDB instance on port 8877
C:\Users\user\node_modules\deepify\node_modules\deep-db\node_modules\local-dynamo\lib\process.js:91
      this._removePidFile();
           ^

TypeError: this._removePidFile is not a function
    at ChildProcess._cleanup (C:\Users\user\node_modules\deepify\node_modules\deep-db\node_modules\local-dynamo\lib\process.js:91:12)
    at emitOne (events.js:82:20)
    at ChildProcess.emit (events.js:169:7)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickDomainCallback (node.js:397:17)

user@user-3 MINGW64 ~
$

**Comment by eistrati** [comment]
@PaulStAmand Thanks for your feedback. It looks like local-dynamo requires JRE v6+ (@see [Windows Configuration](https://github.com/MitocGroup/deep-framework/blob/master/docs/windows.md), step 1). Can you please confirm that your version of JRE is newer then 6.0?

**Comment by eistrati** [comment]
I'll close this issue for now, but please feel free to open if above suggested fix doesn't work for you.
