### ISSUE TITLE
Babel 6 message when deepify executes

### ISSUE THREAD

**Issue by PaulStAmand** [MitocGroup/deep-framework#283]
I'm seeing this message appear as deepify executes under windows 7, unclear on windows 10, havent tried it on that machine yet...

![image](https://cloud.githubusercontent.com/assets/5920528/13707419/8add912e-e777-11e5-93e2-e5ffd7203ca3.png)

the cli command have been moved to babel-cli

comments say to...
npm uninstall babel
npm install babel-cli

**Comment by eistrati** [comment]
Please don't use babel 6 with deepify, because there are serious incompatibility issues which we don't have physical time to fix. Instead, use babel 5 because it's proven to be working fine / stable. So, I'd like to ask you to:

1. `npm uninstall -g babel babel-cli`
2. `npm install -g babel@5.*`

I'll close this issue now, but please feel free to reopen if something doesn't make sense, ok?

**Comment by PaulStAmand** [comment]
Ok I'll look back at this, instructions may need clarification, at some
point something would have indicated I needed it and simply installed the
latest.

I'll remove it and put 5 on both machines.

**Comment by eistrati** [comment]
Yes, I agree with you, we should be more transparent on babel v5 vs v6. We'll update the docs, reflecting this feedback. Thank you!

**Comment by PaulStAmand** [comment]
After I uninstalled babel 6 -g  under git-bash on windows 10 , the parameters started showing up and correctly displaying the description text for the parameter.

**Comment by PaulStAmand** [comment]
under windows 10 the prompting no longer appears nor does execution stop waiting for input with babel 5 installed
hello-world launches correctly, occasionally a return of null occurs rather than the expected output, but it is know appropriately continuing under git-bash

**Comment by eistrati** [comment]
Oh man! :) I'm so sorry for your wasted time, @PaulStAmand ... But it's great that you've figured out that babel v6 was partially the problem. We'll definitely make it much much clear to everybody else NOT to use babel v6 for now!

**Comment by PaulStAmand** [comment]
not at all.  Its a learning process.  There's a lot going on simultaneously.
