### ISSUE TITLE
When session expires request callback is not called

### ISSUE THREAD

**Issue by dragosh1011** [MitocGroup/deep-framework#299]
version: 1.8.18

I'm using amazon identity for login and I set to received token an callback for time expiration.  After amazon_token is expired (~ 1 hour), I send a resource request. The callback for token expiration is called and I can view in network tab bad request to amazon-cognito, but callback from sent request is not called and I don't get any response for it.

**Comment by eistrati** [comment]
Duplicate: https://github.com/MitocGroup/deep-framework/issues/323
