### ISSUE TITLE
[deep-security] Add support for refresh tokens

### ISSUE THREAD

**Issue by GoreA** [MitocGroup/deep-framework#323]
At this moment, session expires in 1 hour even if user is "working" on the web-site. Session should expire only after one hour after last user activity.

**Comment by eistrati** [comment]
More feedback from @dragosh1011:

Version: 1.8.18

I'm using amazon identity for login and I set to received token an callback for time expiration. After amazon_token is expired (~ 1 hour), I send a resource request. The callback for token expiration is called and I can view in network tab bad request to amazon-cognito, but callback from sent request is not called and I don't get any response for it.

**Comment by ivignan** [comment]
@CCristi Is this still relevant?

**Comment by CCristi** [comment]
@ivignan yes

**Comment by avozicov** [comment]
Confirmation testing is Passed.
LiveBook App was used to validate this use case and after 1 hour of inactivity user was still logged in and logout process was successfully performed.
