### ISSUE TITLE
Refactoring unit tests for deep-framework

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/deep-framework#38]
1. Add kernel loading from file.
2. Loading all services by Kernel.get().
3. Fix mocks to have the same aproach

**Comment by vcernomschi** [comment]
This task was divide to atomic tasks:

https://github.com/MitocGroup/deep-framework/issues/46
https://github.com/MitocGroup/deep-framework/issues/47
https://github.com/MitocGroup/deep-framework/issues/48
https://github.com/MitocGroup/deep-framework/issues/49
https://github.com/MitocGroup/deep-framework/issues/50
https://github.com/MitocGroup/deep-framework/issues/51
https://github.com/MitocGroup/deep-framework/issues/52
https://github.com/MitocGroup/deep-framework/issues/53
