### ISSUE TITLE
Multiple errors freeze browser if it is opened for some time

### ISSUE THREAD

**Issue by dragosh1011** [MitocGroup/deep-framework#380]
Version: deep-framework@1.10.8

Issue was reproduced after ~12 hours of idleness.
Multiple errors endlessly appear in console `LoadCredentialsException: Error on loading security credentials in deep-resource -> request. IdentityProviderTokenExpiredException: "test.auth0.com" access_token has expired on "Wed Jun 08 2016 19:10:54 GMT+0300 (EEST)".` and browser becomes completely frozen and inaccessible.
<img width="1244" alt="screen shot 2016-06-17 at 5 10 22 pm" src="https://cloud.githubusercontent.com/assets/11290107/16153337/9a49d026-34ae-11e6-9fa5-3a2be428f1af.png">

**Comment by eistrati** [comment]
Apparently fixed.
