### ISSUE TITLE
Cannot read property 'setLastSyncCount' of undefined

### ISSUE THREAD

**Issue by dragosh1011** [MitocGroup/deep-framework#382]
Version: deep-framework@1.10.8

Cannot read property 'setLastSyncCount' of undefined error appears when user quickly logs in -> logs out two times in a row

<img width="1280" alt="screen shot 2016-06-27 at 4 15 16 pm" src="https://cloud.githubusercontent.com/assets/11290107/16380921/6e5cd90a-3c82-11e6-851f-539787d37bd5.png">

**Comment by ivignan** [comment]
@CCristi Looks like it is not fixed as per @dsasov. Please work with him see where the problem is

**Comment by dsasov** [comment]
<img width="1280" alt="screen_shot_2016-11-25_at_10_45_49_am" src="https://cloud.githubusercontent.com/assets/10956412/20619649/58eedb84-b2fe-11e6-9b5f-a1a5bba50b50.png">

**Comment by dsasov** [comment]
<img width="1277" alt="screen shot 2016-11-28 at 11 37 10 am" src="https://cloud.githubusercontent.com/assets/10956412/20663122/0d1e4f56-b55f-11e6-8914-66679bb266b7.png">
