### ISSUE TITLE
`Error on loading security credentials` - Livebook is not working

### ISSUE THREAD

**Issue by dsasov** [MitocGroup/deep-framework#420]
Both stage and prod environments are not working (login, books list)

![screenshot from 2016-08-22 18 10 41](https://cloud.githubusercontent.com/assets/10956412/17859878/01ba4d12-6894-11e6-9852-bdd7ca9aac8a.png)

**Comment by CCristi** [comment]
Fixed in https://github.com/MitocGroup/deep-framework/pull/421

**Comment by dsasov** [comment]
Issue moved to [MitocGroup/livebook #852](https://github.com/MitocGroup/livebook/issues/852) via [**ZenHub**](https://www.zenhub.com/)
