### ISSUE TITLE
InMemory Cache Driver does not check time to live parameter and returns the whole cached object

### ISSUE THREAD

**Issue by AScripnic** [MitocGroup/deep-framework#444]
When calling

``` javascript
this.kernel.get('security').token.getUser((error, data) => {
  ...
});
```

`error` and `data` are null, even if my `userProviderEndpoint` return correct data and the `this.loggedUserId` property is populated correctly in lambda which calls `getUser(...)` method.

This error is not reproducing every time.

https://github.com/MitocGroup/deep-framework/blob/master/src/deep-security/lib/UserProvider.js#L26 in this `response` property `data` and `error` are null, both.

**UPDATE**

https://github.com/MitocGroup/deep-framework/blob/master/src/deep-cache/lib/Driver/InMemoryDriver.js#L63 - Returns the whole array with ttl in it, but not only value if cache is valid yet

**Comment by eistrati** [comment]
Verified.
