### ISSUE TITLE
deep-session request fails when token expires

### ISSUE THREAD

**Issue by AScripnic** [MitocGroup/deep-framework#461]
deep_session request fails every time with 'Unable to lock dataset: deep_session due to existing lock holder' error

![image](https://cloud.githubusercontent.com/assets/11028782/18996870/b4fba186-873a-11e6-9254-068ab6115910.png)

**Comment by dsasov** [comment]
https://github.com/MitocGroup/deep-framework/issues/473

**Comment by CCristi** [comment]
409 Conflict Exception appears when using the same application from multiple devices. The error is handled internally in deep-security (https://github.com/MitocGroup/deep-framework/blob/master/src/deep-security/lib/TokenManager.js#L193), and doesn't affect framework workflow.

**Comment by eistrati** [comment]
Apparently fixed.
