### ISSUE TITLE
deep-security return invalid security token after page refresh

### ISSUE THREAD

**Issue by AScripnic** [MitocGroup/deep-framework#473]
When calling `deep-security` login method, after page refresh, `securityToken.identityId` is not defined or null.

deep-framework version: deep-framework@1.10.17
browser: safari

**Comment by dsasov** [comment]
Error is still reproducing:

<img width="1280" alt="screen_shot_2016-11-18_at_2_19_51_pm" src="https://cloud.githubusercontent.com/assets/10956412/20429943/48cb3edc-ad9a-11e6-8017-befa85cc0724.png">
