### ISSUE TITLE
Refactoring unit test for deep-resource module

### ISSUE THREAD

**Issue by avozicov** [MitocGroup/deep-framework#51]
Refactoring unit tests for deep-resource module to have the same approach to create Kernel instance from config file.
Loading all services by Kernel.get(). Update/create mocks to have the same approach for all modules.

**Comment by vcernomschi** [comment]
https://github.com/MitocGroup/deep-framework/pull/94

**Comment by vcernomschi** [comment]
Need to make optimization to retrieve resource/action/ in separete class. It takes 1 hr. Moved to next release
