### ISSUE TITLE
[deep-security] UnrecognizedClientException: The security token included in the request is invalid

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/deep-framework#529]
```
{
    "errorMessage": "{\"errorType\":\"UnrecognizedClientException\",\"errorMessage\":\"The security token included in the request is invalid.\",\"errorStack\":\"UnrecognizedClientException: The security token included in the request is invalid.\\n    at Object.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/json.js:43:27)\\n    at Request.extractError (/var/runtime/node_modules/aws-sdk/lib/protocol/rest_json.js:37:8)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:105:20)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:668:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:670:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:77:10)\\n    at Request.emit (/var/runtime/node_modules/aws-sdk/lib/request.js:668:14)\\n    at Request.transition (/var/runtime/node_modules/aws-sdk/lib/request.js:22:10)\\n    at AcceptorStateMachine.runTo (/var/runtime/node_modules/aws-sdk/lib/state_machine.js:14:12)\\n    at /var/runtime/node_modules/aws-sdk/lib/state_machine.js:26:10\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:38:9)\\n    at Request.<anonymous> (/var/runtime/node_modules/aws-sdk/lib/request.js:670:12)\\n    at Request.callListeners (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:115:18)\\n    at callNextListener (/var/runtime/node_modules/aws-sdk/lib/sequential_executor.js:95:12)\\n    at IncomingMessage.onEnd (/var/runtime/node_modules/aws-sdk/lib/event_listeners.js:231:11)\\n    at emitNone (events.js:72:20)\\n    at IncomingMessage.emit (events.js:166:7)\\n    at endReadableNT (_stream_readable.js:905:12)\\n    at nextTickCallbackWith2Args (node.js:437:9)\\n    at process._tickDomainCallback (node.js:392:17)\",\"_deep_error_code_\":500}"
}
```

**Comment by dsasov** [comment]
Bug is still reproducing and it seems to be the general issue. 

It reproduced in deep-account, lambda `account/set-active` failed with 500 error

<img width="765" alt="screen shot 2017-03-13 at 5 20 34 pm" src="https://cloud.githubusercontent.com/assets/10956412/23861027/706b0716-0811-11e7-8780-d94cebda47ee.png">

<img width="1280" alt="screen shot 2017-03-13 at 5 20 27 pm" src="https://cloud.githubusercontent.com/assets/10956412/23861035/7573ed90-0811-11e7-8959-b6ac493ef417.png">

**Comment by mgoria** [comment]
Cannot be reproduced, seems to be fixed by other deep-security recent improvements.

**Comment by mgoria** [comment]
Same steps from https://github.com/MitocGroup/deep-framework/issues/592

**Comment by avozicov** [comment]
**Test Failed**
_The issue is reproducing with the following steps:_
- Install WordPress on local machine 
- Install AdTechMedia Plugin (latest dev release)
- Navigate to AdTechMedia Plugin themes configuration page
- Open browser console and view error logs for "Property Retrieve" Lambda Invocation 

_As a result:_
- Plugin configuration view is broken in UI

_Please refer to attachment for more details:_
<img width="1280" alt="screen shot 2017-06-21 at 12 48 24" src="https://user-images.githubusercontent.com/12330493/27378238-f41f6450-567f-11e7-9fa1-b5397289eac4.png">

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- There should not be errors on calling property-retrieve endpoints 
<img width="1280" alt="screen shot 2017-06-22 at 17 47 01" src="https://user-images.githubusercontent.com/12330493/27440321-0786abc2-5773-11e7-9812-7df177981cb9.png">
