### ISSUE TITLE
restore windows bash [linux subsystem windows 10]

### ISSUE THREAD

**Issue by odick** [MitocGroup/deep-framework#543]
Hi,

I need help on removing deepify_comp.sh from bash start up command
Everytime I start bash on windows 10 cmd, it always show:

**bash: /mnt/c/Users/*username*/AppData/Roaming/npm/node_modules/deepify/hooks/deepify_comp.sh: No such file or directory**

This happen after remove deepify from global npm

Thank you

**Comment by eistrati** [comment]
@odick I'm not sure what is the exact file used in Windows 10 (.profile, .bashrc or .bash_profile), but I've ran something similar on my OS X:

```shell
MitocGroup:~ eugene$ cat ~/.profile | grep deepify
cat: /Volumes/Data/Users/eugene/.profile: No such file or directory
MitocGroup:~ eugene$ cat ~/.bashrc | grep deepify
cat: /Volumes/Data/Users/eugene/.bashrc: No such file or directory
MitocGroup:~ eugene$ cat ~/.bash_profile | grep deepify
. /Volumes/Data/Users/eugene/.nvm/versions/node/v4.3.2/lib/node_modules/deepify/hooks/deepify_comp.sh
```

Try to run similar command on your computer and edit earlier identified file by removing the line that looks like this: `/mnt/c/Users/username/AppData/Roaming/npm/node_modules/deepify/hooks/deepify_comp.sh`

I hope it helps.

**Comment by eistrati** [comment]
I'll close this issue for now, but feel free to open it anytime if you need further assistance.
