### ISSUE TITLE
[deep-fs] readFile from s3 does not work

### ISSUE THREAD

**Issue by ddimitrioglo** [MitocGroup/deep-framework#573]
I'm following the example from the documentation:

```
let system = fs.system;
system.readFile('some/file.txt', function() {
    // ...
});
```

and it woks in my local env as described, but does not work in my lambda after upload.

My use case:
```
const fs = this.kernel.get('fs').private;
fs.readFile(filePath, (err, result) => {
    return (err) ? reject(err) : resolve(result);
});
```

**Comment by AlexanderC** [comment]
Please provide more details like: real file path you want to read, microservice from where you're executing lambda and the microservice the desired file is located

**Comment by ddimitrioglo** [comment]
- File path: `deep.dev.private.430f1fff/pitch/2017/03/27/message.twig`
- Lambda belongs to: `atm-admin` microapp
- I run it manually

**Comment by AlexanderC** [comment]
File system abstraction (`this.kernel.get('fs').private`) uses `private/${microapp-id}` prefix, so a `deep.dev.private.***x*xxx/pitch/2017/03/27/message.twig` path should be like `deep.dev.private.***x*xxx/private/${microapp-id}/pitch/2017/03/27/message.twig` and the `readFile` call should look like `fs.readFile('pitch/2017/03/27/message.twig', ...)`
