### ISSUE TITLE
Add Lambda tags

### ISSUE THREAD

**Issue by ivignan** [MitocGroup/deep-framework#584]
Lambda support tagging - https://aws.amazon.com/releasenotes/5198208415517126

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- Tags should be added to Mitocgroup AWS Account on Lambda function 
<img width="1080" alt="screen shot 2017-06-08 at 14 57 19" src="https://user-images.githubusercontent.com/12330493/26927532-f654523c-4c5a-11e7-85c7-e54875574fd7.png">
