### ISSUE TITLE
Capture aws-sdk calls when x-ray enabled

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/deep-framework#588]
Capture aws-sdk calls when x-ray enabled and add some other custom subsegments to trace deep-framework overhead and deep-kernel boot time.

**Comment by mgoria** [comment]
Related to https://github.com/MitocGroup/deep-package-manager/issues/509

**Comment by mgoria** [comment]
Steps to test:

1. Make sure `xRay|enabled` parameter is set to `true` (ref:  "xRay|enabled": true)
2. Deploy an test application (e.g. todoMVC)
3. Make some calls from frontend
4. Inspect lambda calls into AWS x-ray console https://console.aws.amazon.com/xray/home

**Comment by avozicov** [comment]
**Test Passed**
Acceptance Criteria:
- Lambda Calls should be logged in "AWS X-Ray service" on "Service Map" and "Traces" 
- Create and Update lambdas were used to validate the task 
<img width="1280" alt="screen shot 2017-06-20 at 14 13 27" src="https://user-images.githubusercontent.com/12330493/27330580-a98cc95e-55c2-11e7-96c2-26b45f669279.png">
<img width="1280" alt="screen shot 2017-06-20 at 14 06 18" src="https://user-images.githubusercontent.com/12330493/27330578-a98bb73a-55c2-11e7-8351-ad16faca0aaf.png">
<img width="1280" alt="screen shot 2017-06-20 at 14 06 32" src="https://user-images.githubusercontent.com/12330493/27330579-a98cb2e8-55c2-11e7-8593-a7328b9f9706.png">
<img width="1280" alt="screen shot 2017-06-20 at 14 08 46" src="https://user-images.githubusercontent.com/12330493/27330581-a98e1aa2-55c2-11e7-8fa6-3d9ee9ed05ab.png">
