### ISSUE TITLE
[deep-security] Invalid login token. Issuer doesn't match providerName

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/deep-framework#593]
```
{"__type":"NotAuthorizedException","message":"Invalid login token. Issuer doesn't match providerName"}
```
![screen shot 2017-05-02 at 12 16 04 pm](https://cloud.githubusercontent.com/assets/2959952/25611830/34e66f40-2f31-11e7-8503-f212564b4773.png)

**Comment by mgoria** [comment]
Steps to test:

1. Inspect cognito identity related request (see screenshot above) and look for login provider name it should be a valid one (ref.  http://docs.aws.amazon.com/cognito/latest/developerguide/external-identity-providers.html) not `snapshot` keyword.

**Comment by avozicov** [comment]
**Test Passed**
- On accessing "Admin" page cognito identity request should contain valid login provider name instead of snapshots 
<img width="1280" alt="screen shot 2017-06-19 at 18 44 06" src="https://user-images.githubusercontent.com/12330493/27294253-a005989e-5521-11e7-9967-1af56548493f.png">
