### ISSUE TITLE
Cannot find module "lodash/assign"

### ISSUE THREAD

**Issue by grigoreme** [MitocGroup/deep-framework#606]
After last deep-framework update inside ATM project on start appeared the next error:
![image](https://user-images.githubusercontent.com/25903855/27071841-21f4e67a-5027-11e7-9ea3-c0453337b8ca.png)
This error is reproduced on Mac and Linux as well.
deep-framework@1.12.36 - fail
deep-framework@1.12.31 - ok

**Comment by avozicov** [comment]
**Test Passed**
- There should not be "deep-framework" related errors on accessing "Admin" component
<img width="1280" alt="screen shot 2017-06-19 at 19 04 31" src="https://user-images.githubusercontent.com/12330493/27294443-4146cf98-5522-11e7-8d6d-d8176fcefb05.png">
