### ISSUE TITLE
Error 'Missing CognitoIdentityServiceProvider in aws-sdk@2.70.0'

### ISSUE THREAD

**Issue by mgoria** [MitocGroup/deep-framework#618]
This error is thrown when AWS temp credentials are expired and deep-framework tries to refresh them.

![28780361-18048f72-760f-11e7-95b5-4208fa2ed274](https://user-images.githubusercontent.com/2959952/29525913-d4402f50-869c-11e7-9b0d-ead840d5562e.png)

**Comment by eistrati** [comment]
Done.
